name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Poetry
      run: python -m pip install poetry

    - name: Install Dependencies using Poetry
      run: poetry install

    - name: Lint with flake8
      run: poetry run python -m flake8 app

    - name: Run pytest
      run: poetry run python -m pytest app/tests.py